("Afeganistão - afegão"),
("Andorra - andorrano"),
("Angola - angolano"),
("Antígua e Barbuda - antiguano"),
("Argélia - argelino"),
("Argentina - argentino"),
("Armênia - armênio"),
("Austrália - australiano"),
("Áustria - austríaco"),
("Azerbaijão - azeri"),
("Bahamas - bahamense"),
("Bangladesh - bangladês"),
("Barbados - barbadiano"),
("Barém - baremita"),
("Bielorrússia - bielorrusso"),
("Bélgica - belga"),
("Belize - belizenho"),
("Benim - beninense"),
("Bolívia - boliviano"),
("Bósnia e Herzegovina - bósnio"),
("Botsuana - bechuano"),
("Brasil - brasileiro"),
("Brunei - bruneano"),
("Bulgária - búlgaro"),
("BurkinaFaso - burquinense"),
("Burundi - burundês"),
("Butão - butanense"),
("Cabo Verde - cabo-verdiano"),
("Camarões - camaronense"),
("Camboja - cambojano"),
("Canadá - canadense"),
("República Centro-Africana - centroafricano"),
("Chade - chadiano"),
("China - chinês"),
("Chile - chileno"),
("Ilhas Cook - cookiano"),
("Colômbia - colombiano"),
("Comores - comoriano"),
("Costa Rica - costa-riquenho"),
("Croácia - croata"),
("Cuba - Cubano"),
("Chipre - cipriota"),
("República Tcheca - tcheco"),
("República Democrática do Congo - congolense"),
("Dinamarca - dinamarquês"),
("Djibuti - djibutiense"),
("Dominica - dominiquense"),
("República Dominicana - dominicano"),
("Timor Leste - timorense"),
("Equador - equatoriano"),
("Egito - egípcio"),
("El Salvador - salvadorenho"),
("Inglaterra - inglês"),
("Guiné Equatorial - guinéu-equatoriano"),
("Eritreia - eritreu"),
("Estônia - estoniano"),
("Fiji - fijiano"),
("Finlândia - finlandês"),
("França - francês"),
("Gabão - gabonense"),
("Gâmbia - gambiano"),
("Geórgia - geórgico"),
("Alemanha - alemão"),
("Granada - granadino"),
("Grécia - grego"),
("Guatemala - guatemalteco"),
("Guiné - guineano"),
("GuinéBissau - guineense"),
("Guiana - guianense"),
("Haiti - haitiano"),
("Holanda - holandês"),
("Honduras - hondurenho"),
("Hungria - húngaro"),
("Islândia - islandês"),
("Índia - indiano"),
("Indonésia - indonésio"),
("Irã - iraniano"),
("Irlanda - irlandês"),
("Israel - israelita"),
("Itália - italiano"),
("Costa do Marfim - costa-marfinense"),
("Jamaica - jamaicano"),
("Japão - japonês"),
("Jordânia - jordão"),
("Cazaquistão - cazaque"),
("Quênia - queniano"),
("Quiribati - I-quiribatiano"),
("Quirguistão - quirguistanês"),
("Kuwait - kuwaitiano"),
("Laos - laosiano"),
("Letônia - letoniano"),
("Líbano - libanês"),
("Lesoto - lesotiano"),
("Libéria - liberiano"),
("Liechtenstein - liechtensteinense"),
("Lituânia - lituano"),
("Luxemburgo - luxemburguês"),
("Líbia - líbio"),
("Macedônia - macedônio"),
("Madagascar - madagascarense"),
("Malásia - malaio"),
("Malaui - malauiano"),
("Maldivas - maldivo"),
("Máli - maliano"),
("Malta - maltês"),
("Maurício - mauriciano"),
("Mauritânia - mauritano"),
("Ilhas Marshall - marshallino"),
("Estados Federados da Micronésia - micronésio"),
("México - mexicano"),
("Marrocos - marroquino"),
("Moldavia - moldávio"),
("Mônaco - monegasco"),
("Mongólia - mongol"),
("Montenegro - montenegrino"),
("Moçambique - moçambicano"),
("Myanmar - birmanês"),
("Namíbia - namibiano"),
("Nauru - nauruano"),
("Nepal - nepalês"),
("Nova Zelândia - neozelandês"),
("Nicarágua - nicaraguense"),
("Níger - nigerino"),
("Nigéria - nigeriano"),
("Niue - niuano"),
("Coréia do Norte - norte-coreano"),
("Noruega - norueguês"),
("Omã - omanense"),
("Palestina - palestino"),
("Paquistão - paquistanês"),
("Palau - palauense"),
("Panamá - panamenho"),
("Papua Nova Guiné - papuásio"),
("Paraguai - paraguaio"),
("Peru - peruano"),
("Philippines - filipino"),
("Polônia - polonês"),
("Portugal - português"),
("Catar - catarense"),
("Romênia - romeno"),
("Rússia - russo"),
("Ruanda - ruandês"),
("Samoa - samoano"),
("Santa Lúcia - santa-lucense"),
("São Cristóvão e Nevis - são-cristovense"),
("São Marino - são-marinense"),
("São Tomé e Príncipe - são-tomense"),
("São Vicente e Granadinas - são-vicentino"),
("Escócia - escocês"),
("Senegal - senegalense"),
("Sérvia - sérvio"),
("Seicheles - seichelense"),
("Serra Leoa - serra-leonês"),
("Singapura - singapurense"),
("Eslováquia - eslovaco"),
("Ilhas Salomão - salomônico"),
("Somália - somali"),
("África do Sul - sul–africano"),
("Coréia do Sul - coreano"),
("Sudão do Sul - sul-sudanense"),
("Espanha - espanhol"),
("Sri Lanka - srilankês"),
("Sudão - sudanense"),
("Suriname - surinamês"),
("Suazilândia - suazi"),
("Suécia - sueco"),
("Suíça - suíço"),
("Síria - sírio"),
("Tadiquistão - tajique"),
("Tanzânia - tanzaniano"),
("Tailândia - tailandês"),
("Togo - togolês"),
("Tonga - tonganês"),
("Trindade e Tobago - trinitário"),
("Tunísia - tunisiano"),
("Turcomenistão - turcomeno"),
("Turquia - turco"),
("Tuvalu - tuvaluano"),
("Ucrânia - ucraniano"),
("Uganda - ugandês"),
("Uruguai - uruguaio"),
("Emirados Árabes Unidos - árabe"),
("Reino Unido - britânico"),
("Estados Unidos - americano"),
("Usbequistão - uzbeque"),
("Vanuatu - vanuatuano"),
("Venezuela - venezuelano"),
("Vietnã - vietnamita"),
("País de Gales - galês"),
("Iêmen - iemenita"),
("Zâmbia - zambiano"),
("Zimbábue - zimbabueano");