("Afeganistão", "Afegão"),
("Andorra", "Andorrano"),
("Angola", "Angolano"),
("Antígua e Barbuda", "Antiguano"),
("Argélia", "Argelino"),
("Argentina", "Argentino"),
("Armênia", "Armênio"),
("Austrália", "Australiano"),
("Áustria", "Austríaco"),
("Azerbaijão", "Azeri"),
("Bahamas", "Bahamense"),
("Bangladesh", "Bangladês"),
("Barbados", "Barbadiano"),
("Barém", "Baremita"),
("Bielorrússia", "Bielorrusso"),
("Bélgica", "Belga"),
("Belize", "Belizenho"),
("Benim", "Beninense"),
("Bolívia", "Boliviano"),
("Bósnia e Herzegovina", "Bósnio"),
("Botsuana", "Bechuano"),
("Brasil", "Brasileiro"),
("Brunei", "Bruneano"),
("Bulgária", "Búlgaro"),
("BurkinaFaso", "Burquinense"),
("Burundi", "Burundês"),
("Butão", "Butanense"),
("Cabo Verde", "Cabo-verdiano"),
("Camarões", "Camaronense"),
("Camboja", "Cambojano"),
("Canadá", "Canadense"),
("República Centro-Africana", "Centroafricano"),
("Chade", "Chadiano"),
("China", "Chinês"),
("Chile", "Chileno"),
("Ilhas Cook", "Cookiano"),
("Colômbia", "Colombiano"),
("Comores", "Comoriano"),
("Costa Rica", "Costa-riquenho"),
("Croácia", "Croata"),
("Cuba", "Cubano"),
("Chipre", "Cipriota"),
("República Tcheca", "Tcheco"),
("República Democrática do Congo", "Congolense"),
("Dinamarca", "Dinamarquês"),
("Djibuti", "Djibutiense"),
("Dominica", "Dominiquense"),
("República Dominicana", "Dominicano"),
("Timor Leste", "Timorense"),
("Equador", "Equatoriano"),
("Egito", "Egípcio"),
("El Salvador", "Salvadorenho"),
("Inglaterra", "Inglês"),
("Guiné Equatorial", "Guinéu-equatoriano"),
("Eritreia", "Eritreu"),
("Estônia", "Estoniano"),
("Fiji", "Fijiano"),
("Finlândia", "Finlandês"),
("França", "Francês"),
("Gabão", "Gabonense"),
("Gâmbia", "Gambiano"),
("Geórgia", "Geórgico"),
("Alemanha", "Alemão"),
("Granada", "Granadino"),
("Grécia", "Grego"),
("Guatemala", "Guatemalteco"),
("Guiné", "Guineano"),
("GuinéBissau", "Guineense"),
("Guiana", "Guianense"),
("Haiti", "Haitiano"),
("Holanda", "Holandês"),
("Honduras", "Hondurenho"),
("Hungria", "Húngaro"),
("Islândia", "Islandês"),
("Índia", "Indiano"),
("Indonésia", "Indonésio"),
("Irã", "Iraniano"),
("Irlanda", "Irlandês"),
("Israel", "Israelita"),
("Itália", "Italiano"),
("Costa do Marfim", "Costa-marfinense"),
("Jamaica", "Jamaicano"),
("Japão", "Japonês"),
("Jordânia", "Jordão"),
("Cazaquistão", "Cazaque"),
("Quênia", "Queniano"),
("Quiribati", "I-quiribatiano"),
("Quirguistão", "Quirguistanês"),
("Kuwait", "Kuwaitiano"),
("Laos", "Laosiano"),
("Letônia", "Letoniano"),
("Líbano", "Libanês"),
("Lesoto", "Lesotiano"),
("Libéria", "Liberiano"),
("Liechtenstein", "Liechtensteinense"),
("Lituânia", "Lituano"),
("Luxemburgo", "Luxemburguês"),
("Líbia", "Líbio"),
("Macedônia", "Macedônio"),
("Madagascar", "Madagascarense"),
("Malásia", "Malaio"),
("Malaui", "Malauiano"),
("Maldivas", "Maldivo"),
("Máli", "Maliano"),
("Malta", "Maltês"),
("Maurício", "Mauriciano"),
("Mauritânia", "Mauritano"),
("Ilhas Marshall", "Marshallino"),
("Estados Federados da Micronésia", "Micronésio"),
("México", "Mexicano"),
("Marrocos", "Marroquino"),
("Moldavia", "Moldávio"),
("Mônaco", "Monegasco"),
("Mongólia", "Mongol"),
("Montenegro", "Montenegrino"),
("Moçambique", "Moçambicano"),
("Myanmar", "Birmanês"),
("Namíbia", "Namibiano"),
("Nauru", "Nauruano"),
("Nepal", "Nepalês"),
("Nova Zelândia", "Neozelandês"),
("Nicarágua", "Nicaraguense"),
("Níger", "Nigerino"),
("Nigéria", "Nigeriano"),
("Niue", "Niuano"),
("Coréia do Norte", "Norte-coreano"),
("Noruega", "Norueguês"),
("Omã", "Omanense"),
("Palestina", "Palestino"),
("Paquistão", "Paquistanês"),
("Palau", "Palauense"),
("Panamá", "Panamenho"),
("Papua Nova Guiné", "Papuásio"),
("Paraguai", "Paraguaio"),
("Peru", "Peruano"),
("Philippines", "Filipino"),
("Polônia", "Polonês"),
("Portugal", "Português"),
("Catar", "Catarense"),
("Romênia", "Romeno"),
("Rússia", "Russo"),
("Ruanda", "Ruandês"),
("Samoa", "Samoano"),
("Santa Lúcia", "Santa-lucense"),
("São Cristóvão e Nevis", "São-cristovense"),
("São Marino", "São-marinense"),
("São Tomé e Príncipe", "São-tomense"),
("São Vicente e Granadinas", "São-vicentino"),
("Escócia", "Escocês"),
("Senegal", "Senegalense"),
("Sérvia", "Sérvio"),
("Seicheles", "Seichelense"),
("Serra Leoa", "Serra-leonês"),
("Singapura", "Singapurense"),
("Eslováquia", "Eslovaco"),
("Ilhas Salomão", "Salomônico"),
("Somália", "Somali"),
("África do Sul", "Sul–africano"),
("Coréia do Sul", "Coreano"),
("Sudão do Sul", "Sul-sudanense"),
("Espanha", "Espanhol"),
("Sri Lanka", "Srilankês"),
("Sudão", "Sudanense"),
("Suriname", "Surinamês"),
("Suazilândia", "Suazi"),
("Suécia", "Sueco"),
("Suíça", "Suíço"),
("Síria", "Sírio"),
("Tadiquistão", "Tajique"),
("Tanzânia", "Tanzaniano"),
("Tailândia", "Tailandês"),
("Togo", "Togolês"),
("Tonga", "Tonganês"),
("Trindade e Tobago", "Trinitário"),
("Tunísia", "Tunisiano"),
("Turcomenistão", "Turcomeno"),
("Turquia", "Turco"),
("Tuvalu", "Tuvaluano"),
("Ucrânia", "Ucraniano"),
("Uganda", "Ugandês"),
("Uruguai", "Uruguaio"),
("Emirados Árabes Unidos", "Árabe"),
("Reino Unido", "Britânico"),
("Estados Unidos", "Americano"),
("Usbequistão", "Uzbeque"),
("Vanuatu", "Vanuatuano"),
("Venezuela", "Venezuelano"),
("Vietnã", "Vietnamita"),
("País de Gales", "Galês"),
("Iêmen", "Iemenita"),
("Zâmbia", "Zambiano"),
("Zimbábue", "Zimbabueano");